### PR TITLE
Fix compilation error introduced with fc5ef6de6 (#1184)

### PR DESCRIPTION
**Pull request by deining**

### CODE REVIEW

**Comment by remkop** [comment]
Last-minute rushed changes, never good... :-(
Thanks for the fix!
